title: Rushkoff Archive
description: Douglas Rushkoff's Article Archive
author: Douglas Rushkoff
unpublished: false
# This is used to narrow the the google search. Used in the `site:` parameter
search_domain: archive.rushkoff.com
collections:
  # Define our collections and their properties
  articles:
    item_desc: Article
    output: true
  publications:
    item_desc: Publication
    output: true
  categories:
    item_desc: Category
    output: true
  videos_elsewhere:
    item_desc: Video
    output: true
  misc_elsewhere:
    item_desc: Misc
    output: true
defaults:
  # Set the default front-matter fields for various content types
  - scope:
      path: ''
      type: 'articles'
    values:
      layout: 'article'
  - scope:
      path: ''
      type: 'publications'
    values:
      layout: 'publication'
  - scope:
      path: ''
      type: 'categories'
    values:
      layout: 'category'
  - scope:
      path: ''
      type: 'videos_elsewhere'
    values:
      layout: 'video_elsewhere'
  - scope:
      path: ''
      type: 'misc_elsewhere'
    values:
      layout: 'article'
plugins:
  - jekyll-remote-theme
  - jekyll-feed
feed:
  collections:
    - articles
rushkoff:
  sidebar:
    categories:
      # Sets the categories in the sidebar index.  Note, the urls
      # need to point to existing pages.  Specifically, if a sidebar
      # category "Journalism" exists linking to /categories/journalism.html,
      # then the "categories" collection must exist and include a category
      # "journalism".
      - title: Journalism
        url: /categories/journalism.html
      - title: Book Chapters
        url: /categories/book-chapters.html
      - title: Scholarship
        url: /categories/scholarship.html
      - title: Fiction & Misc
        url: /categories/fiction-miscellaneous.html
      - title: Everything
        url: /index.html
    more_categories:
      # Like categories, but made distinct, by spacing it below.
      - title: Sort By Publication
        url: /publications.html
